### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by trufanov-nok** [n7275/PinesnormOrbiter#1]
https://github.com/n7275/PinesnormOrbiter/blob/0a126e70e4a0478acbc444b04f18f533e284e9ef/gravTest/gravTest.cpp#LL267C16-L267C16

Shouldn't it be `if (m != (maxDegree + 2)) {` ?
in article it's
![image](https://github.com/n7275/PinesnormOrbiter/assets/5746456/0b382193-b671-4b77-a333-00525aa92c86)

And this has a sense as `anm(m+1,` will overflow otherwise.

**Comment by trufanov-nok** [comment]
I guess `if (m < maxDegree) {` next to it shall be `if (m < maxDegree+1) {` too.

**Comment by n7275** [comment]
I don't believe so, but I could be wrong. The code in the paper is MATLAB code, so indices start at 1, whereas in my code they start at 0. 

I did fix an off-by-one error somewhere in my PR to Orbiter though, but I can't remember exactly where right now. https://github.com/orbitersim/orbiter/pull/239/files

**Comment by trufanov-nok** [comment]
I'm keeping in mind matlabs' indices and still think it's a bug. And it seems it was in PR too.    

They have a loop `for M = 0:NMAX+2 %RAE` which is quite C-stylish and they address Matlab's 1-based indices with `M_A = M + 1;` variable inside this loop. So when one port the code to C he may just replace `MA` with `M` and make array access 0-based.   
So they have 0-based indices in `for` loops and 1-based in actual access to array.   

The if clause at line 267 means "if not the last row", bcs otherwise they'll be out of bounds.  
And the next `if` at line 271 should work (according to the matlabs code) till `for`-loop below it could be called at least once:
![image](https://github.com/n7275/PinesnormOrbiter/assets/5746456/f3a64cb5-b606-4493-b352-ec100356e7e4)
Last acceptable m is nmax and for loop will be  `n = nmax + 2; n <= nmax+2;`
In your case the last call will be `n = maxDegree + 1; n <= maxDegree+2;` so for-loop makes 2 iterations.

Btw, I can't find this PR in Orbiter's code. Was it merged in?

**Comment by n7275** [comment]
It has not been merged yet. I will try testing the changes you recommend. I appreciate you looking into this. Out of curiosity, do I know you from Orbiter-Forum? I don't remember your name, but maybe it's just been a while.

**Comment by trufanov-nok** [comment]
> do I know you from Orbiter-Forum? I don't remember your name, but maybe it's just been a while

nope. I just googled out your post by keywords "20160011252.pdf c++". I'm performing a QA of a proprietary pinesnorm implementation and it's pretty hard to find anything to compare with except for original matlab code and fortran code in https://jacobwilliams.github.io/Fortran-Astrodynamics-Toolkit/proc/pinesnorm.html

**Comment by n7275** [comment]
Thanks,

If that change works, feel free to pull-request it.

I have a forum thread here, if you were ever interested in joining. https://www.orbiter-forum.com/threads/improved-tesseral-gravity-model.40266

My main motivation in implementing this is having a realistic environment for flying simulated Apollo missions in. I'm a developer for another project called NASSP, which is an addon for Orbiter and simulates Apollo hardware: https://github.com/orbiternassp/NASSP

**Comment by trufanov-nok** [comment]
Hi,
> If that change works, feel free to pull-request it.
It seems to change almost nothing if model degree is big enough as this affects the last Pnm coefficient of the model. 

You better push the changes on your own as I'm on linux machine and there might be CR/LF problems with line endings. Also github's online editor says  "We’ve detected the file encoding as windows-1252. When you commit changes we will transcode it to UTF-8." which might be unwanted.


> I have a forum thread here, if you were ever interested in joining.

Good to know. Thanks

**Comment by n7275** [comment]
This should now be fixed by 4b9893f99cb77d50d124b9c7665a8cf21c21780f

**Comment by n7275** [comment]
...darn I broke some text encoding with that
